/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.busreservationsystem;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ruksh
 */
public class Bookings extends javax.swing.JFrame {

    private Connection conn = DBConnection.getConnection();  // Initialize connection

    public Bookings() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtusermail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtusernumber = new javax.swing.JTextField();
        txtusermail4 = new javax.swing.JTextField();
        btnbook1 = new javax.swing.JButton();
        btncancel1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtstarting = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtending = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtbusnumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comboTime = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        btnprofile = new javax.swing.JButton();
        btnBus = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncancel2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("QUICK BOOKING");

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("E-mail");

        txtusermail.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("Booking ID");

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel12.setText("Mobile Number");

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel13.setText("Date");

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel14.setText("Name");

        btnbook1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnbook1.setText("Book ");
        btnbook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbook1ActionPerformed(evt);
            }
        });

        btncancel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btncancel1.setText("Cancel");
        btncancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Starting Point");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Ending Point");

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel15.setText("Time");

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel16.setText("Bus Number");

        comboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8.00 AM -9.00 AM", "10.00AM-11.00 AM", "12.00 PM-1.00 PM", "2.00 PM-3.00 PM", "4.00 PM-5.00 PM", "6.00 PM-7.00 PM", "8.00 PM-9.00 PM", "10.00 PM-11.00 PM", "12.00 AM-1.00 AM", "2.00 AM-3.00 AM", "4.00 AM-5.00 AM", "6.00 AM-7.00 AM" }));
        comboTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTimeActionPerformed(evt);
            }
        });

        btnprofile.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnprofile.setText("Profile");
        btnprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofileActionPerformed(evt);
            }
        });

        btnBus.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnBus.setText("Bus");
        btnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchAvailableBus(evt);
            }
        });

        btnhome.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel3.setText("Book Your Spot for a Comfortable Ride!");

        btncancel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btncancel2.setText("Go to Waiting List");
        btncancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addComponent(txtbusnumber))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtusermail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtusermail4)
                                    .addComponent(txtusernumber)
                                    .addComponent(txtusername)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtstarting)
                                    .addComponent(txtending)
                                    .addComponent(comboTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(btnprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btncancel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnbook1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btncancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)))))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtusermail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusermail4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtusernumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstarting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(comboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbook1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancel2)
                .addGap(49, 49, 49))
        );

        jPanel4.setBackground(new java.awt.Color(158, 6, 6));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(158, 6, 6));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbook1ActionPerformed
        String email = txtusermail4.getText().trim();
        String name = txtusername.getText().trim();
        String mobile = txtusernumber.getText().trim();

// Get the date from jDateChooser
        java.util.Date date = jDateChooser.getDate();
        String formattedDate = new SimpleDateFormat("yyyy-MM-dd").format(date);

        String startingPoint = txtstarting.getText().trim();
        String endingPoint = txtending.getText().trim();

        if (startingPoint.isEmpty() || endingPoint.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both Starting and Ending points!");
            return;
        }

        try {
            if (conn != null) {
                String query = "SELECT bus_number, total_seats FROM Buses_Reg WHERE starting_point = ? AND ending_point = ?";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, startingPoint);
                pstmt.setString(2, endingPoint);

                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    txtbusnumber.setText(rs.getString("bus_number"));
                    int totalSeats = rs.getInt("total_seats");

                    // Check if next seat number exceeds total seats for the selected date
                    String getSeatQuery = "SELECT ISNULL(MAX(seat_number), 0) + 1 AS next_seat_number FROM Bookings WHERE bus_number = ? AND Date = ?";
                    pstmt = conn.prepareStatement(getSeatQuery);
                    pstmt.setString(1, txtbusnumber.getText().trim());
                    pstmt.setString(2, formattedDate);
                    rs = pstmt.executeQuery();

                    int nextSeatNumber = 1; // Default seat number in case the table is empty
                    if (rs.next()) {
                        nextSeatNumber = rs.getInt("next_seat_number");
                    }

                    if (nextSeatNumber > totalSeats) {
                        int response = JOptionPane.showConfirmDialog(this, "The bus has reached its seat limit for the selected date. Would you like to be added to the waiting list?", "Waiting List", JOptionPane.YES_NO_OPTION);
                        if (response == JOptionPane.YES_OPTION) {
                            // Redirect to waiting list form
                            String insertWaitingListQuery = "INSERT INTO [Bus_Reservation_System].[dbo].[Waiting_List] (email, name, mobile_number, Date, starting_point, ending_point, bus_number, Time) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                            pstmt = conn.prepareStatement(insertWaitingListQuery);
                            pstmt.setString(1, email);
                            pstmt.setString(2, name);
                            pstmt.setString(3, mobile);
                            pstmt.setString(4, formattedDate);
                            pstmt.setString(5, startingPoint);
                            pstmt.setString(6, endingPoint);
                            pstmt.setString(7, txtbusnumber.getText().trim());
                            pstmt.setString(8, (String) comboTime.getSelectedItem());

                            int rowsInserted = pstmt.executeUpdate();
                            if (rowsInserted > 0) {
                                JOptionPane.showMessageDialog(this, "You have been added to the waiting list.");
                                clearFields();
                            } else {
                                JOptionPane.showMessageDialog(this, "Failed to add to the waiting list!");
                            }
                        }
                    } else {
                        String busnumber = txtbusnumber.getText().trim();
                        String time = (String) comboTime.getSelectedItem();

                        if (email.isEmpty() || name.isEmpty() || mobile.isEmpty()
                                || startingPoint.isEmpty() || endingPoint.isEmpty() || busnumber.isEmpty() || time.isEmpty()) {
                            JOptionPane.showMessageDialog(this, "All fields are required!");
                            return;
                        }

                        String insertQuery = "INSERT INTO Bookings (email, name, mobile_number, Date, starting_point, ending_point, bus_number, Time, status, seat_number) "
                                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                        pstmt = conn.prepareStatement(insertQuery);
                        pstmt.setString(1, email);
                        pstmt.setString(2, name);
                        pstmt.setString(3, mobile);
                        pstmt.setString(4, formattedDate);
                        pstmt.setString(5, startingPoint);
                        pstmt.setString(6, endingPoint);
                        pstmt.setString(7, busnumber);
                        pstmt.setString(8, time);
                        pstmt.setString(9, "Booked"); // Automatically set status to "Booked"
                        pstmt.setInt(10, nextSeatNumber); // Set the next available seat number

                        int rowsInserted = pstmt.executeUpdate();
                        if (rowsInserted > 0) {
                            JOptionPane.showMessageDialog(this, "Your booking has been successfully completed. Confirmation details have been sent to your email and phone number.");
                            clearFields();
                        } else {
                            JOptionPane.showMessageDialog(this, "Booking Failed!");
                        }
                    }
                } else {
                    txtbusnumber.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Database connection is null!");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
        }

    }// Method to fetch and fill bus number dynamically

    private void autoFillBusNumber() {
        String startingPoint = txtstarting.getText().trim();
        String endingPoint = txtending.getText().trim();

        // Validate that both fields are not empty
        if (!startingPoint.isEmpty() && !endingPoint.isEmpty()) {
            try {
                Connection connection = DBConnection.getConnection();
                if (connection != null) {
                    String query = "SELECT bus_number FROM Buses_Reg WHERE starting_point = ? AND ending_point = ?";
                    PreparedStatement pstmt = connection.prepareStatement(query);
                    pstmt.setString(1, startingPoint);
                    pstmt.setString(2, endingPoint);

                    ResultSet rs = pstmt.executeQuery();

                    if (rs.next()) {
                        txtbusnumber.setText(rs.getString("bus_number"));
                    } else {
                        txtbusnumber.setText(""); // Clear the field if no matching bus is found
                    }

                    connection.close();
                } else {
                    JOptionPane.showMessageDialog(this, "Database connection is null!");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
            }
        } else {
            txtbusnumber.setText(""); // Clear the field if inputs are incomplete
        }


    }//GEN-LAST:event_btnbook1ActionPerformed
    private void clearFields() {
        txtusermail4.setText("");
        txtusername.setText("");
        txtusernumber.setText("");
        txtstarting.setText("");
        txtending.setText("");
        txtbusnumber.setText("");
        comboTime.setSelectedIndex(0);
        jDateChooser.setDate(new java.util.Date()); // Reset jDateChooser to the current date
    }
    private void btncancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel1ActionPerformed
        dispose(); // Close the application
    }//GEN-LAST:event_btncancel1ActionPerformed

    private void comboTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTimeActionPerformed

    private void btnprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofileActionPerformed
        this.setVisible(false);
        new Profile().setVisible(true);
    }//GEN-LAST:event_btnprofileActionPerformed

    private void fetchAvailableBus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchAvailableBus
        btnBus.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fetchAvailableBus();
            }
        });

    }

    private void fetchAvailableBus() {
        String startingPoint = txtstarting.getText().trim();
        String endingPoint = txtending.getText().trim();
        String selectedTime = comboTime.getSelectedItem() != null ? comboTime.getSelectedItem().toString() : "";

        // Input validation
        if (startingPoint.isEmpty() || endingPoint.isEmpty() || selectedTime.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Starting Point, Ending Point, and select Time.");
            return;
        }

        try {
            // Establishing connection
            Connection connection = DBConnection.getConnection();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed!");
                return;
            }

            // SQL query with time condition
            String query = "SELECT bus_number FROM Buses_Reg WHERE starting_point = ? AND ending_point = ? AND time = ?";
            PreparedStatement pstmt = connection.prepareStatement(query);
            pstmt.setString(1, startingPoint);
            pstmt.setString(2, endingPoint);
            pstmt.setString(3, selectedTime);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // Display the available bus number
                txtbusnumber.setText(rs.getString("bus_number"));
            } else {
                // If no matching bus found
                txtbusnumber.setText("No Bus Found");
                JOptionPane.showMessageDialog(this, "No available buses for the selected route and time.");
            }

            // Close the connection
            connection.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_fetchAvailableBus

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btncancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel2ActionPerformed
        this.setVisible(false);
        new Waitinglist().setVisible(true);
    }//GEN-LAST:event_btncancel2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBus;
    private javax.swing.JButton btnbook1;
    private javax.swing.JButton btncancel1;
    private javax.swing.JButton btncancel2;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnprofile;
    private javax.swing.JComboBox<String> comboTime;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtbusnumber;
    private javax.swing.JTextField txtending;
    private javax.swing.JTextField txtstarting;
    private javax.swing.JTextField txtusermail;
    private javax.swing.JTextField txtusermail4;
    private javax.swing.JTextField txtusername;
    private javax.swing.JTextField txtusernumber;
    // End of variables declaration//GEN-END:variables
}
